name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy the Docker image
      run: |
        docker build -t udagram-api-feed ./udagram-api-feed
        docker tag udagram-api-feed richiiestowie/udagram-api-feed
        docker build -t udagram-api-user ./udagram-api-user
        docker tag udagram-api-user richiiestowie/udagram-api-user
        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend richiiestowie/udagram-frontend
        docker build -t reverseproxy ./udagram-reverseproxy
        docker tag reverseproxy richiiestowie/udagram-reverseproxy
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push richiiestowie/udagram-api-feed
        docker push richiiestowie/udagram-api-user
        docker push richiiestowie/udagram-frontend
        docker push richiestowie/udagram-reverseproxy